/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kingsch.bot.Post;

import kingsch.bot.*;
import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.InputSource;

/**
 * @author zakir
 */
public class Posting extends javax.swing.JFrame {

    /**
     * Creates new form KingschPosting
     */
    public Posting() {
        initComponents();
        readaccounts();
    }

    int totalacc;

    private void readaccounts() {
        String line = "";
        String splitBy = ",";
        totalacc = 0;
        try {
            BufferedReader br = new BufferedReader(new FileReader("C:\\Program Files\\Common Files\\CSVS\\Account.csv"));
            Counting:
            while ((line = br.readLine()) != null) //returns a Boolean value
            {
                String[] email = line.split(splitBy);    // use comma as separator
                if (!(email[0].contains("@"))) {
                    continue Counting; // skip Counting
                }
                totalacc = totalacc + 1;
            }

            for (int i = 1; i < totalacc + 1; i++) {
                System.out.println(i);

                // get the model from the jtable
                DefaultTableModel model = (DefaultTableModel) ContainingTable.getModel();

                // insert row to the model from jtextfields using addRow method
                model.addRow(new Object[]{i, "", ""});
            }

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ContainingTable = new javax.swing.JTable();
        Start = new javax.swing.JButton();
        Stop = new javax.swing.JButton();
        ImagePath = new javax.swing.JTextField();
        idLBL = new javax.swing.JLabel();
        Comments = new javax.swing.JTextField();
        imageLBL1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        TXTurl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imageLBL = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TXTurl1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ContainingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Text", "Image", "time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ContainingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContainingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ContainingTable);

        Start.setBackground(new java.awt.Color(102, 255, 255));
        Start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Start.setLabel("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        Stop.setBackground(new java.awt.Color(0, 255, 255));
        Stop.setText("Stop");
        Stop.setToolTipText("");
        Stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopActionPerformed(evt);
            }
        });

        ImagePath.setText("Image Path");
        ImagePath.setEnabled(false);
        ImagePath.setMaximumSize(new java.awt.Dimension(62, 20));
        ImagePath.setMinimumSize(new java.awt.Dimension(62, 20));
        ImagePath.setPreferredSize(new java.awt.Dimension(162, 20));
        ImagePath.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                ImagePathInputMethodTextChanged(evt);
            }
        });

        idLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLBL.setText("Id");

        Comments.setText("Comment");
        Comments.setEnabled(false);
        Comments.setMaximumSize(new java.awt.Dimension(62, 20));
        Comments.setMinimumSize(new java.awt.Dimension(62, 20));
        Comments.setPreferredSize(new java.awt.Dimension(162, 20));
        Comments.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                CommentsInputMethodTextChanged(evt);
            }
        });

        imageLBL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLBL1.setText("Image");
        imageLBL1.setToolTipText("");

        jButton4.setText("Insert");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Text");

        jLabel2.setText("Image");

        imageLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLBL.setText("Image");
        imageLBL.setToolTipText("");
        imageLBL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Time");

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Choose");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(imageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXTurl, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXTurl1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTurl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imageLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTurl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLBL1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Comments, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imageLBL1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Start, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Stop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login(WebDriver driver, String email) {
        driver.findElement(By.xpath("//*[@placeholder=\"Username, Phone Number or E-mail\"]")).sendKeys(email);
        driver.findElement(By.xpath("//*[@placeholder=\"Password\"]")).sendKeys("Q123456789");
        driver.findElement(By.xpath("(//*[@class=\"submit-btn\"])[1]")).click();

    }

    private void StartingPost(WebDriver driver, String Text, String ImageurL) {
        writingText:
        while (true) {
            try {
                String myString = Text;
                StringSelection stringSelection = new StringSelection(myString);
                Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
                clipboard.setContents(stringSelection, null);

                Actions actions = new Actions(driver);

                driver.findElement(By.xpath("//*[@placeholder=\"What's happening?\"]")).click();  //comment
                actions.keyDown(Keys.CONTROL);
                actions.sendKeys("v").build().perform();
                actions.keyUp(Keys.CONTROL);

                break writingText;
            } catch (Exception e) {
            }
        }
        if (!(ImageurL == "")) {
            inputtingfile:
            while (true) {
                try {
                    driver.findElement(By.xpath("//*[@type=\"file\"]")).sendKeys(ImageurL);  //file
                    Thread.sleep(5000);
                    break inputtingfile;
                } catch (Exception e) {
                }
            }
        }
        Posting:
        while (true) {
            try {
                driver.findElement(By.xpath("//div[contains(text(), \"Post to Timeline\")]")).click();  //post
                break Posting;
            } catch (Exception e) {
            }
        }
    }
    public ChromeDriver driver;

    private static void unzip(Path source, Path target) throws IOException {

        try ( ZipInputStream zis = new ZipInputStream(new FileInputStream(source.toFile()))) {

            // list files in zip
            ZipEntry zipEntry = zis.getNextEntry();

            while (zipEntry != null) {

                boolean isDirectory = false;
                // example 1.1
                // some zip stored files and folders separately
                // e.g data/
                //     data/folder/
                //     data/folder/file.txt
                if (zipEntry.getName().endsWith(File.separator)) {
                    isDirectory = true;
                }

                Path newPath = zipSlipProtect(zipEntry, target);

                if (isDirectory) {
                    java.nio.file.Files.createDirectories(newPath);
                } else {

                    // example 1.2
                    // some zip stored file path only, need create parent directories
                    // e.g data/folder/file.txt
                    if (newPath.getParent() != null) {
                        if (java.nio.file.Files.notExists(newPath.getParent())) {
                            java.nio.file.Files.createDirectories(newPath.getParent());
                        }
                    }

                    // copy files, nio
                    Files.copy(zis, newPath, StandardCopyOption.REPLACE_EXISTING);

                    zis.close();
                    // copy files, classic
                    /*try (FileOutputStream fos = new FileOutputStream(newPath.toFile())) {
                        byte[] buffer = new byte[1024];
                        int len;
                        while ((len = zis.read(buffer)) > 0) {
                            fos.write(buffer, 0, len);
                        }
                    }*/
                }

                zipEntry = zis.getNextEntry();

            }
            zis.closeEntry();

        }

    }
    // protect zip slip attack

    public static Path zipSlipProtect(ZipEntry zipEntry, Path targetDir)
            throws IOException {

        // test zip slip vulnerability
        // Path targetDirResolved = targetDir.resolve("../../" + zipEntry.getName());
        Path targetDirResolved = targetDir.resolve(zipEntry.getName());

        // make sure normalized file still has targetDir as its prefix
        // else throws exception
        Path normalizePath = targetDirResolved.normalize();
        if (!normalizePath.startsWith(targetDir)) {
            throw new IOException("Bad zip entry: " + zipEntry.getName());
        }

        return normalizePath;
    }

    private void OpenAndUpdateDriver(String url) throws Exception {
        boolean update = false;
        String ChromeVersion = "";
        String ChromeDriverVersion = "";
        while (true) {
            if (update == true) {

                //Get Chromedriver Path
                BufferedReader reader = null;
                URL urlLink = new URL("https://chromedriver.storage.googleapis.com/?delimiter=/&prefix=" + ChromeVersion);
                reader = new BufferedReader(new InputStreamReader(urlLink.openStream()));
                String s = null;
                while ((s = reader.readLine()) != null) {
                    break;
                }

                InputSource textSource = new InputSource(new StringReader(s));
                DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();

                DocumentBuilder builder = factory.newDocumentBuilder();

                Document doc = builder.parse(textSource);
                NodeList nodelist = doc.getElementsByTagName("Prefix");

                Element element = (Element) nodelist.item(nodelist.getLength() - 2);
                ChromeDriverVersion = element.getTextContent();

                String Destination = "ChromeDriver\\chromedriver_win32.zip";
                String link = "https://chromedriver.storage.googleapis.com/" + ChromeDriverVersion + "chromedriver_win32.zip";
                //Closing ChromeDriver
                KingschAccount.StatusLBL.setText("Closing ChromeDriver");
                try {
                    Runtime.getRuntime().exec("taskkill /F /IM chromedriver.exe");
                } catch (Exception e) {
                };
                KingschAccount.StatusLBL.setText("Closed ChromeDriver");
                KingschAccount.StatusLBL.setText("Deleting Old ChromeDriver...");
                File Des = new File("ChromeDriver\\chromedriver.exe");
                //Deleting Existed one
                Des.delete();

                KingschAccount.StatusLBL.setText("Downloading Latest ChromeDriver...");
                URL urlChromeDriver = new URL(link);
                HttpURLConnection http = (HttpURLConnection) urlChromeDriver.openConnection();
                double fileSize = (double) http.getContentLengthLong();
                BufferedInputStream in = new BufferedInputStream(http.getInputStream());
                FileOutputStream fos = null;
                try {
                    fos = new FileOutputStream(Destination);
                } catch (Exception e) {
                    System.out.println(e);
                }
                //Closing ChromeDriver
                KingschAccount.StatusLBL.setText("Closing ChromeDriver");
                try {
                    Runtime.getRuntime().exec("taskkill /F /IM chromedriver.exe");
                } catch (Exception e) {
                };
                KingschAccount.StatusLBL.setText("Closed ChromeDriver");
                BufferedOutputStream bout = new BufferedOutputStream(fos, 1024);

                byte[] buffer = new byte[1024];
                double downloaded = 0.00;
                int read = 0;
                double percentDownloaded = 0.00;
                while ((read = in.read(buffer, 0, 1024)) >= 0) {
                    bout.write(buffer, 0, read);
                    downloaded += read;
                    percentDownloaded = (downloaded * 100) / fileSize;
                    String percent = String.format("%.2f", percentDownloaded);
                    KingschAccount.StatusLBL.setText(percent + "% Downloaded");
                }

                reader.close();
                bout.close();
                fos.close();
                in.close();
                Thread.sleep(1000);
                //Closing ChromeDriver
                KingschAccount.StatusLBL.setText("Closing ChromeDriver");
                try {
                    Runtime.getRuntime().exec("taskkill /F /IM chromedriver.exe");
                } catch (Exception e) {
                };
                KingschAccount.StatusLBL.setText("Closed ChromeDriver");
                Thread.sleep(1000);
                //Uzipping
                KingschAccount.StatusLBL.setText("Uzipping");
                Path source = Paths.get("ChromeDriver/chromedriver_win32.zip");
                Path target = Paths.get("ChromeDriver/");

                try {

                    unzip(source, target);
                    System.out.println("Done");

                } catch (IOException e) {
                    e.printStackTrace();
                }

                KingschAccount.StatusLBL.setText("Uzipped");

            }

            try {
                KingschAccount.StatusLBL.setText("Starting...");
                System.setProperty("webdriver.chrome.driver", "ChromeDriver\\chromedriver.exe");
                ChromeOptions options = new ChromeOptions();
                options.addArguments("--mute-audio");
                KingschAccount.StatusLBL.setText("Adding extension...");
                options.addExtensions(new File("C:\\Program Files\\Common Files\\ChromeDriver\\anticaptcha.crx"));
                DesiredCapabilities capabilities = new DesiredCapabilities();
                capabilities.setCapability(ChromeOptions.CAPABILITY, options);
                KingschAccount.StatusLBL.setText("Setting...");
                driver = new ChromeDriver(capabilities);
                driver.navigate().to(url);
                break;
            } catch (Exception e) {
                // String to be scanned to find the pattern.
                String line = e.getMessage();
                String pattern = "[0-9]+[.]";
                // Create a Pattern object
                Pattern r = Pattern.compile(pattern);
                // Now create matcher object.
                Matcher m = r.matcher(line);
                if (m.find()) {
                    ChromeVersion = m.group(0);
                }

                update = true;
                continue;
            }
        }

    }

    private void posting(WebDriver driver) {

    }
    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        DefaultTableModel model = (DefaultTableModel) ContainingTable.getModel();
        all:
        for (int i = 0; i < model.getRowCount(); i++) {
            String TextTBL = model.getValueAt(i, 1).toString();
            if (TextTBL.isEmpty()) {
                continue all;
            }
            BufferedReader br = null;
            String Email = "";
            String Text = model.getValueAt(i, 1).toString();
            String Image = model.getValueAt(i, 2).toString();

            try {
                br = new BufferedReader(new FileReader("C:\\Program Files\\Common Files\\CSVS\\Account.csv"));
                String line = "";
                int linecount = 0;
                String splitBy = ",";
                Reading:
                while ((line = br.readLine()) != null) {

                    if (i == linecount) {
                        String[] email = line.split(splitBy);    // use comma as separator
                        Email = email[0];
                        break Reading;
                    }
                    linecount = linecount + 1;
                }
            } catch (Exception e) {
            }
            try {
                OpenAndUpdateDriver("https://accounts.kingsch.at/?client_id=com.kingschat&scopes=%5B%22kingschat%22%5D&redirect_uri=https%3A%2F%2Fweb.kingsch.at%2Ftimeline");
                login(driver, Email);

            } catch (Exception e) {
            }
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
            StartingPost(driver, Text, Image);

            driver.quit();
        }
    }//GEN-LAST:event_StartActionPerformed

    private void StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopActionPerformed

    }//GEN-LAST:event_StopActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
//            DefaultTableModel model = (DefaultTableModel) ContainingTable.getModel();
//            model.setValueAt(selectedFile.getAbsolutePath(), Integer.parseInt(idLBL.getText()) - 1, 2);
            ImagePath.setText(selectedFile.getAbsolutePath());
            imageLBL.setText("<html><img src=\"file:" + selectedFile.getAbsolutePath() + "\" width=160 height=50/><html>");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContainingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContainingTableMouseClicked
        int row = ContainingTable.rowAtPoint(evt.getPoint());
        int col = ContainingTable.columnAtPoint(evt.getPoint());
        DefaultTableModel model = (DefaultTableModel) ContainingTable.getModel();
        idLBL.setText(model.getValueAt(row, 0).toString());
        Comments.setText(model.getValueAt(row, 1).toString());
        imageLBL.setText("<html><img src=\"file:" + model.getValueAt(row, 2).toString() + "\" width=160 height=50/><html>");

        ImagePath.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_ContainingTableMouseClicked

    private void ImagePathInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ImagePathInputMethodTextChanged

    }//GEN-LAST:event_ImagePathInputMethodTextChanged

    private void CommentsInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_CommentsInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentsInputMethodTextChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) ContainingTable.getModel();
        //model.addRow(new Object[]{TXTurl.getText(), jTextArea1.getText()});
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Posting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Posting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Posting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Posting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Posting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Comments;
    private javax.swing.JTable ContainingTable;
    private javax.swing.JTextField ImagePath;
    private javax.swing.JButton Start;
    private javax.swing.JButton Stop;
    private javax.swing.JTextField TXTurl;
    private javax.swing.JTextField TXTurl1;
    private javax.swing.JLabel idLBL;
    private javax.swing.JLabel imageLBL;
    private javax.swing.JLabel imageLBL1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
